/*
OWNER: Integrated Planning Team
PURPOSE: Outbound shipment volume from import distribution centers
FEATURES: Teradata SQL, Multi-source UNION, Storage/Flow facility routing
PLATFORM: Teradata
*/

-- OUTBOUND SHIPMENTS FROM IDCs
SELECT
    'PART-2' AS PART_NO,
    CAL.YEAR_WK_NBR AS SHIP_WEEK_NO,
    CASE
        WHEN PO_TYPE IN (43, 45, 46) AND INV_HDR.SHIP_FROM_DC_NBR = 6060 THEN 7089
        WHEN PO_TYPE IN (43, 45, 46) AND INV_HDR.SHIP_FROM_DC_NBR = 6061 THEN 7086
        WHEN PO_TYPE IN (43, 45, 46) AND INV_HDR.SHIP_FROM_DC_NBR = 6088 THEN 7093
        WHEN PO_TYPE IN (43, 45, 46) AND INV_HDR.SHIP_FROM_DC_NBR = 7042 THEN 7085
        WHEN PO_TYPE IN (43, 45, 46) AND INV_HDR.SHIP_FROM_DC_NBR = 7078 THEN 7094
        WHEN PO_TYPE IN (43, 45, 46) AND INV_HDR.SHIP_FROM_DC_NBR = 7067 THEN 8695
        ELSE INV_HDR.SHIP_FROM_DC_NBR
    END AS FROM_LOCATION_NO,
    INV_HDR.SHIP_TO_STORE_NBR AS TO_LOCATION_NO,
    CAL1.YEAR_WK_NBR AS RECEIPT_WEEK_NO,
    INV_LINE.ITEM_NBR AS LEGACY_ITEM_NO,
    I.ITEM_NBR AS ITEM_NO,
    I.ACCTG_DEPT_NBR AS DEPT_NO,
    I.DEPT_CATEGORY_NBR AS DEPT_CATEGORY_NO,
    CASE WHEN I.VNPK_QTY = 0 THEN 1 ELSE I.VNPK_QTY END AS VNPK_QTY,
    CASE WHEN I.WHPK_QTY = 0 THEN 1 ELSE I.WHPK_QTY END AS WHPK_QTY,
    I.WHPK_CUBE_QTY,
    I.WHPK_CUBE_UOM_CODE,
    
    -- Total shipped units with variable weight handling
    COALESCE(SUM(CASE
        WHEN INV_LINE.VARIABLE_WT_QTY > 1 
        THEN ROUND(INV_LINE.EACH_SHIP_QTY / INV_LINE.VARIABLE_WT_QTY + 0.4999) * I.VNPK_QTY
        ELSE ROUND(CAST(INV_LINE.EACH_SHIP_QTY AS DECIMAL(18,2)))
    END), 0.0) AS TOTAL_SHIP_UNITS,
    
    -- Vendor pack quantity
    SUM(CASE
        WHEN INV_LINE.VARIABLE_WT_QTY > 1 
        THEN ROUND(INV_LINE.EACH_SHIP_QTY / INV_LINE.VARIABLE_WT_QTY + 0.4999)
        ELSE (CAST(INV_LINE.EACH_SHIP_QTY AS DECIMAL(18,2)) / I.VNPK_QTY)
    END) AS TOT_VNPK_SHIP_QTY,
    
    SUM(INV_LINE.TOT_WHPK_SHIP_QTY) AS TOTAL_WHPK_SHIP_QTY,
    SUM(INV_LINE.TOT_WHPK_SHIP_QTY) * I.WHPK_CUBE_QTY AS TOTAL_CUBE_QTY_IN_CF,
    
    SUM(CASE
        WHEN INV_LINE.VARIABLE_WT_QTY > 1 
        THEN ROUND(INV_LINE.EACH_SHIP_QTY / INV_LINE.VARIABLE_WT_QTY + 0.4999)
        ELSE (CAST(INV_LINE.EACH_SHIP_QTY AS DECIMAL(18,2)) / I.VNPK_QTY)
    END * I.VNPK_CUBE_QTY) AS TOTAL_VNPK_CUBE_QTY_IN_CF,
    
    SUM(INV_LINE.EXT_COST_AMT) AS EXT_COST_AMT,
    SUM(INV_LINE.EXT_RETAIL_AMT) AS EXT_RETAIL_AMT

FROM DC_INVOICE AS INV_HDR
    
    INNER JOIN DC_INVOICE_LINE AS INV_LINE
        ON INV_LINE.INVOICE_NBR = INV_HDR.INVOICE_NBR
        AND INV_LINE.INVOICE_DATE = INV_HDR.INVOICE_DATE
        AND INV_LINE.INVOICE_DATE BETWEEN DATE - 21 AND DATE
    
    INNER JOIN ITEM_DIM AS I
        ON I.MDS_FAM_ID = INV_LINE.ITEM_NBR
        AND I.COUNTRY_CODE = 'US'
        AND I.CURRENT_IND = 'Y'
        AND I.DEPT_NBR NOT IN (15, 37, 38, 39, 49, 58, 60, 65, 69, 75, 85, 86, 88, 89, 99)
    
    INNER JOIN CALENDAR_DIM AS CAL
        ON CAL.CALENDAR_DATE = INV_LINE.INVOICE_DATE
    
    INNER JOIN (
        SELECT *
        FROM DC_LANE
        WHERE FROM_LOCATION_NBR IN (6060, 6061, 6088, 7042, 7067, 7078)
    ) AS DL
        ON INV_HDR.SHIP_FROM_DC_NBR = DL.FROM_LOCATION_NBR
        AND INV_HDR.SHIP_TO_STORE_NBR = DL.TO_LOCATION_NBR
    
    INNER JOIN CALENDAR_DIM AS CAL1
        ON CAL1.CALENDAR_DATE = INV_HDR.INVOICE_DATE + COALESCE(DL.LEAD_TIME, 0)
    
    LEFT JOIN PURCHASE_ORDER AS PO
        ON INV_LINE.PO_NBR = PO.PO_NBR
        AND INV_LINE.LABEL_DATE >= PO.ORDER_DATE
        AND INV_LINE.LABEL_DATE - PO.ORDER_DATE < 180

WHERE
    INV_HDR.INVOICE_DATE BETWEEN DATE - 60 AND DATE
    AND SHIP_FROM_DC_NBR IN (6060, 6061, 6088, 7042, 7067, 7078)

GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13

UNION

-- TYPE 23 TRANSFER POs
SELECT
    'PART-3' AS PART_NO,
    CAL.YEAR_WK_NBR AS SHIP_WEEK_NO,
    PO.XFER_WHSE_NBR AS FROM_LOCATION_NO,
    INV_HDR.SHIP_FROM_DC_NBR AS TO_LOCATION_NO,
    CAL1.YEAR_WK_NBR AS RECEIPT_WEEK_NO,
    INV_LINE.ITEM_NBR AS LEGACY_ITEM_NO,
    I.ITEM_NBR AS ITEM_NO,
    I.ACCTG_DEPT_NBR AS DEPT_NO,
    I.DEPT_CATEGORY_NBR AS DEPT_CATEGORY_NO,
    CASE WHEN I.VNPK_QTY = 0 THEN 1 ELSE I.VNPK_QTY END AS VNPK_QTY,
    CASE WHEN I.WHPK_QTY = 0 THEN 1 ELSE I.WHPK_QTY END AS WHPK_QTY,
    I.WHPK_CUBE_QTY,
    I.WHPK_CUBE_UOM_CODE,
    
    COALESCE(SUM(CASE
        WHEN INV_LINE.VARIABLE_WT_QTY > 1 
        THEN ROUND(INV_LINE.EACH_SHIP_QTY / INV_LINE.VARIABLE_WT_QTY + 0.4999) * I.VNPK_QTY
        ELSE ROUND(CAST(INV_LINE.EACH_SHIP_QTY AS DECIMAL(18,2)))
    END), 0.0) AS TOTAL_SHIP_UNITS,
    
    SUM(CASE
        WHEN INV_LINE.VARIABLE_WT_QTY > 1 
        THEN ROUND(INV_LINE.EACH_SHIP_QTY / INV_LINE.VARIABLE_WT_QTY + 0.4999)
        ELSE (CAST(INV_LINE.EACH_SHIP_QTY AS DECIMAL(18,2)) / I.VNPK_QTY)
    END) AS TOT_VNPK_SHIP_QTY,
    
    SUM(INV_LINE.TOT_WHPK_SHIP_QTY) AS TOTAL_WHPK_SHIP_QTY,
    SUM(INV_LINE.TOT_WHPK_SHIP_QTY) * I.WHPK_CUBE_QTY AS TOTAL_CUBE_QTY_IN_CF,
    
    SUM(CASE
        WHEN INV_LINE.VARIABLE_WT_QTY > 1 
        THEN ROUND(INV_LINE.EACH_SHIP_QTY / INV_LINE.VARIABLE_WT_QTY + 0.4999)
        ELSE (CAST(INV_LINE.EACH_SHIP_QTY AS DECIMAL(18,2)) / I.VNPK_QTY)
    END * I.VNPK_CUBE_QTY) AS TOTAL_VNPK_CUBE_QTY_IN_CF,
    
    SUM(INV_LINE.EXT_COST_AMT) AS EXT_COST_AMT,
    SUM(INV_LINE.EXT_RETAIL_AMT) AS EXT_RETAIL_AMT

FROM DC_INVOICE AS INV_HDR
    
    INNER JOIN DC_INVOICE_LINE AS INV_LINE
        ON INV_LINE.INVOICE_NBR = INV_HDR.INVOICE_NBR
        AND INV_LINE.INVOICE_DATE = INV_HDR.INVOICE_DATE
        AND INV_LINE.INVOICE_DATE BETWEEN DATE - 21 AND DATE
    
    INNER JOIN ITEM_DIM AS I
        ON I.MDS_FAM_ID = INV_LINE.ITEM_NBR
    
    INNER JOIN PURCHASE_ORDER AS PO
        ON INV_LINE.PO_NBR = PO.PO_NBR
        AND INV_LINE.LABEL_DATE >= PO.ORDER_DATE
        AND INV_LINE.LABEL_DATE - PO.ORDER_DATE < 180
        AND PO.PO_TYPE = 23
        AND PO.ORDER_DATE BETWEEN DATE - 210 AND DATE
        AND PO.XFER_WHSE_NBR IN (6060, 6061, 6088, 7042, 7067, 7078)
    
    INNER JOIN DC_LANE AS DL
        ON PO.XFER_WHSE_NBR = DL.FROM_LOCATION_NBR
        AND INV_HDR.SHIP_FROM_DC_NBR = DL.TO_LOCATION_NBR
    
    INNER JOIN CALENDAR_DIM AS CAL
        ON CAL.CALENDAR_DATE = PO.ORDER_DATE
    
    INNER JOIN CALENDAR_DIM AS CAL1
        ON CAL1.CALENDAR_DATE = PO.ORDER_DATE + COALESCE(DL.LEAD_TIME, 0)

GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
;
