/*
OWNER: Integrated Planning Team
PURPOSE: Distribution center inbound volume projections for planning tools
FEATURES: Teradata SQL, Complex CASE logic, Receipt date offsetting, UNION patterns
PLATFORM: Teradata
*/

-- OPEN POs - PROJECTED INBOUND VOLUME
SELECT
    PART_NO,
    PO_NBR AS PO_NO,
    PO_TYPE,
    CHANNEL_MTHD_CD,
    CHANNEL_MTHD_DESC,
    EVENT_CODE,
    EVENT_CODE_DESC,
    ORDER_DATE,
    COALESCE(SHIP_DATE_ACTUAL, SHIP_DATE_EXPECTED) AS SHIP_DATE,
    IDC_DATE_ACTUAL AS RECEIPT_DATE,
    PORT_DATE_PLANNED AS LATEST_PORT_DATE,
    IDC_DATE_PLANNED AS EST_DEST_ARRIVAL_DATE,
    FROM_LOCATION_NO,
    FROM_LOCATION_TYPE,
    VENDOR_NAME,
    TO_LOCATION_NO_ACTUAL AS TO_LOCATION_NO,
    TO_LOCATION_TYPE_ACTUAL AS TO_LOCATION_TYPE,
    ITEM_NBR AS ITEM_NO,
    MDS_FAM_ID AS LEGACY_ITEM_NO,
    ACCTG_DEPT_NBR AS ACCT_DEPT,
    ORDER_DEPT_NBR AS ORDER_DEPT,
    SUM(UNIT_ORD_QTY - UNIT_RCV_QTY_NEW) AS PO_UNITS,
    SUM(VNPK_ORD_QTY - VNPK_RCV_QTY_NEW) AS PO_CASES

FROM (

SELECT
    RPOS.*,
    
    -- Find first receipt date across all distribution on a booking PO
    MIN(IDC_DATE_ACTUAL - COALESCE(DC_LANE.LEAD_TIME, 0)) OVER (
        PARTITION BY BK_PO_NBR, MDS_FAM_ID
    ) AS MIN_IDC_DATE,
    
    -- Total vendor packs ordered across booking PO
    SUM(VNPK_ORD_QTY) OVER (
        PARTITION BY BK_PO_NBR, MDS_FAM_ID
    ) AS TOT_VNPK_ORD_QTY,
    
    -- Total vendor packs received across booking PO
    SUM(VNPK_RCV_QTY) OVER (
        PARTITION BY BK_PO_NBR, MDS_FAM_ID
    ) AS TOT_VNPK_RCV_QTY,
    
    -- Flag for orders requiring receipt date offset
    CASE
        WHEN ECOMMERCE_IND = 'Y' THEN 'Y'
        WHEN TO_LOCATION_NO_ACTUAL = 7092 THEN 'Y'
        WHEN PO_TYPE IN (40, 42) AND CHANNEL_MTHD_DESC = 'FLOW' THEN 'Y'
        ELSE 'N'
    END AS NEW_RECEIPT_FLAG,
    
    -- Modified receipt date logic
    CASE
        WHEN NEW_RECEIPT_FLAG = 'Y' 
            AND COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED) >= CURRENT_DATE - 21 
            AND (TOT_VNPK_RCV_QTY / TOT_VNPK_ORD_QTY) < 0.5 
        THEN COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED)
        WHEN NEW_RECEIPT_FLAG = 'Y' 
        THEN IDC_DATE_ACTUAL - COALESCE(DC_LANE.LEAD_TIME, 0)
        ELSE IDC_DATE_ACTUAL
    END AS IDC_DATE_ACTUAL_NEW,
    
    -- Modified volume to fill gaps where volume hasn't received downstream
    CASE
        WHEN NEW_RECEIPT_FLAG = 'Y' 
            AND UNIT_RCV_QTY = 0 
            AND COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED) BETWEEN CURRENT_DATE - 21 AND DATE - 1 
        THEN UNIT_ORD_QTY
        ELSE UNIT_RCV_QTY
    END AS UNIT_RCV_QTY_NEW,
    
    CASE
        WHEN NEW_RECEIPT_FLAG = 'Y' 
            AND UNIT_RCV_QTY = 0 
            AND COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED) BETWEEN CURRENT_DATE - 21 AND DATE - 1 
        THEN VNPK_ORD_QTY
        ELSE VNPK_RCV_QTY
    END AS VNPK_RCV_QTY_NEW

FROM (
    -- Receipt quantities and dates with enrichment
    SELECT
        PART_NO,
        PO_NBR,
        BK_PO_NBR,
        ORDER_DATE,
        PO_TYPE,
        EVENT_CODE,
        EVENT_CODE_DESC,
        I.MDS_FAM_ID,
        I.ITEM_NBR,
        I.ACCTG_DEPT_NBR,
        ORDER_DEPT_NBR,
        I.DEPT_CATEGORY_NBR,
        CASE
            WHEN I.BUYING_REGION_CODE = 6 THEN 'Y'
            WHEN EVENT_CODE LIKE '%ONLINE%' THEN 'Y'
            ELSE 'N'
        END AS ECOMMERCE_IND,
        I.CONVEYABLE_IND,
        CHANNEL_MTHD_CD,
        CHANNEL_MTHD_DESC,
        (I.VENDOR_NBR * 1000 + I.VENDOR_DEPT_NBR * 10 + I.VENDOR_SEQ_NBR) AS FROM_LOCATION_NO,
        'VENDOR' AS FROM_LOCATION_TYPE,
        I.VENDOR_NAME,
        TO_LOCATION_NO_PLANNED,
        TO_LOCATION_TYPE_PLANNED,
        TO_LOCATION_NO_ACTUAL,
        TO_LOCATION_TYPE_ACTUAL,
        DC_NBR,
        SHIP_DATE_PLANNED,
        SHIP_DATE_EXPECTED,
        SHIP_DATE_ACTUAL,
        ORIG_PORT_DATE,
        PORT_DATE_PLANNED,
        PORT_DATE_EXPECTED,
        PORT_DATE_ACTUAL,
        IDC_DATE_PLANNED,
        IDC_DATE_EXPECTED,
        IDC_DATE_ACTUAL,
        RDC_DATE_PLANNED,
        RDC_DATE_EXPECTED,
        STORE_DATE_PLANNED,
        STORE_DATE_EXPECTED,
        CLOSE_DATE,
        
        VNPK_ORD_QTY,
        VNPK_ORD_QTY * I.VNPK_QTY AS UNIT_ORD_QTY,
        VNPK_ORD_QTY * I.VNPK_CUBE_QTY AS CUBE_ORD_QTY,
        VNPK_ORD_QTY * I.VNPK_WEIGHT_QTY AS WGT_ORD_QTY,
        (VNPK_ORD_QTY * I.VNPK_QTY) * I.BASE_UNIT_RETAIL_AMT AS RETAIL_ORD_QTY,
        
        VNPK_RCV_QTY,
        VNPK_RCV_QTY * I.VNPK_QTY AS UNIT_RCV_QTY,
        VNPK_RCV_QTY * I.VNPK_CUBE_QTY AS CUBE_RCV_QTY,
        VNPK_RCV_QTY * I.VNPK_WEIGHT_QTY AS WGT_RCV_QTY,
        (VNPK_RCV_QTY * I.VNPK_QTY) * I.BASE_UNIT_RETAIL_AMT AS RETAIL_RCV_QTY

    FROM BASE_ORDER_DATA AS T1
        INNER JOIN ITEM_DIM AS I
            ON I.ITEM_NBR = T1.ITEM_NBR
            AND I.COUNTRY_CODE = 'US'
            AND I.CURRENT_IND = 'Y'
            AND I.DEPT_NBR NOT IN (15, 37, 38, 39, 49, 58, 60, 65, 69, 75, 85, 86, 88, 89, 99)
) AS RPOS

    LEFT JOIN DC_LANE
        ON RPOS.TO_LOCATION_NO_ACTUAL = DC_LANE.FROM_LOCATION_NBR
        AND RPOS.DC_NBR = DC_LANE.TO_LOCATION_NBR

) AS T2

WHERE IDC_DATE_PLANNED > DATE - 30

GROUP BY
    PART_NO, PO_NBR, PO_TYPE, CHANNEL_MTHD_CD, CHANNEL_MTHD_DESC,
    EVENT_CODE, EVENT_CODE_DESC, ORDER_DATE,
    COALESCE(SHIP_DATE_ACTUAL, SHIP_DATE_EXPECTED),
    IDC_DATE_ACTUAL, PORT_DATE_PLANNED, IDC_DATE_PLANNED,
    FROM_LOCATION_NO, FROM_LOCATION_TYPE, VENDOR_NAME,
    TO_LOCATION_NO_ACTUAL, TO_LOCATION_TYPE_ACTUAL,
    ITEM_NBR, MDS_FAM_ID, ACCTG_DEPT_NBR, ORDER_DEPT_NBR
;
