/*
OWNER: Integrated Planning Team
PURPOSE: Actual received volume for import distribution centers
FEATURES: Teradata SQL, Receipt date windowing, Volume fill-in logic
PLATFORM: Teradata
*/

-- RECEIVED POs - ACTUAL INBOUND VOLUME
SELECT
    PART_NO,
    PO_NBR AS PO_NO,
    PO_TYPE,
    CHANNEL_MTHD_CD,
    CHANNEL_MTHD_DESC,
    TRIM(EVENT_CODE) AS EVENT_CODE,
    EVENT_CODE_DESC,
    ORDER_DATE,
    COALESCE(SHIP_DATE_ACTUAL, SHIP_DATE_EXPECTED) AS SHIP_DATE,
    CAST(NULL AS DATE) AS INVOICE_DATE,
    STORE_DATE_PLANNED AS IN_STORE_DATE,
    STORE_DATE_EXPECTED AS EST_IN_STORE_DATE,
    CLOSE_DATE,
    RDC_DATE_PLANNED AS MABD,
    CAST(NULL AS DATE) AS FIRST_RCPT_DATE,
    CAST(NULL AS DATE) AS LAST_RCPT_DATE,
    ORIG_PORT_DATE,
    PORT_DATE_PLANNED AS PORT_DATE,
    PORT_DATE_EXPECTED AS ETA_DATE,
    PORT_DATE_ACTUAL AS ARRIVAL_DATE,
    IDC_DATE_PLANNED AS IDC_DATE,
    RDC_DATE_PLANNED AS PO_RDC_RCPT,
    CAST(NULL AS DATE) AS FISCAL_RCPT_DATE,
    IDC_DATE_PLANNED AS EST_FISCAL_RCPT_DATE,
    FROM_LOCATION_NO,
    VENDOR_NAME,
    TO_LOCATION_NO_ACTUAL AS TO_LOCATION_NO,
    TO_LOCATION_NO_PLANNED,
    ITEM_NBR AS ITEM_NO,
    MDS_FAM_ID AS LEGACY_ITEM_NO,
    ACCTG_DEPT_NBR AS ACCT_DEPT,
    ORDER_DEPT_NBR AS ORDER_DEPT,
    DEPT_CATEGORY_NBR AS DEPT_CATG_NBR,
    SUM(UNIT_RCV_QTY_NEW) AS PO_UNITS,
    SUM(VNPK_RCV_QTY_NEW) AS PO_VNDRPK,
    SUM(RETAIL_RCV_QTY) AS PO_DOLLARS,
    SUM(CUBE_RCV_QTY) AS PO_CUBE,
    FROM_LOCATION_TYPE,
    'DC' AS TO_LOCATION_TYPE,
    IDC_DATE_ACTUAL_NEW AS RECEIPT_DATE

FROM (
    SELECT
        RPOS.*,
        
        -- Find first receipt across booking PO
        MIN(IDC_DATE_ACTUAL - COALESCE(DC_LANE.LEAD_TIME, 0)) OVER (
            PARTITION BY BK_PO_NBR, MDS_FAM_ID
        ) AS MIN_IDC_DATE,
        
        -- Total ordered/received across booking PO
        SUM(VNPK_ORD_QTY) OVER (PARTITION BY BK_PO_NBR, MDS_FAM_ID) AS TOT_VNPK_ORD_QTY,
        SUM(VNPK_RCV_QTY) OVER (PARTITION BY BK_PO_NBR, MDS_FAM_ID) AS TOT_VNPK_RCV_QTY,
        
        -- Receipt offset flag
        CASE
            WHEN ECOMMERCE_IND = 'Y' THEN 'Y'
            WHEN TO_LOCATION_NO_ACTUAL = 7092 THEN 'Y'
            WHEN PO_TYPE IN (40, 42) AND CHANNEL_MTHD_DESC = 'FLOW' THEN 'Y'
            ELSE 'N'
        END AS NEW_RECEIPT_FLAG,
        
        -- Adjusted receipt date
        CASE
            WHEN NEW_RECEIPT_FLAG = 'Y' 
                AND COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED) >= CURRENT_DATE - 21 
                AND (TOT_VNPK_RCV_QTY / TOT_VNPK_ORD_QTY) < 0.5 
            THEN COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED)
            WHEN NEW_RECEIPT_FLAG = 'Y' 
            THEN IDC_DATE_ACTUAL - COALESCE(DC_LANE.LEAD_TIME, 0)
            ELSE IDC_DATE_ACTUAL
        END AS IDC_DATE_ACTUAL_NEW,
        
        -- Adjusted quantities
        CASE
            WHEN NEW_RECEIPT_FLAG = 'Y' AND UNIT_RCV_QTY = 0 
                AND COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED) >= CURRENT_DATE - 21 
            THEN UNIT_ORD_QTY
            ELSE UNIT_RCV_QTY
        END AS UNIT_RCV_QTY_NEW,
        
        CASE
            WHEN NEW_RECEIPT_FLAG = 'Y' AND VNPK_RCV_QTY = 0 
                AND COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED) >= CURRENT_DATE - 21 
            THEN VNPK_ORD_QTY
            ELSE VNPK_RCV_QTY
        END AS VNPK_RCV_QTY_NEW,
        
        CASE
            WHEN NEW_RECEIPT_FLAG = 'Y' AND RETAIL_RCV_QTY = 0 
                AND COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED) >= CURRENT_DATE - 21 
            THEN RETAIL_ORD_QTY
            ELSE RETAIL_RCV_QTY
        END AS RETAIL_RCV_QTY_NEW,
        
        CASE
            WHEN NEW_RECEIPT_FLAG = 'Y' AND CUBE_RCV_QTY = 0 
                AND COALESCE(MIN_IDC_DATE, IDC_DATE_PLANNED) >= CURRENT_DATE - 21 
            THEN CUBE_ORD_QTY
            ELSE CUBE_RCV_QTY
        END AS CUBE_RCV_QTY_NEW

    FROM RECEIPT_POSITION_DATA AS RPOS
        LEFT JOIN DC_LANE
            ON RPOS.TO_LOCATION_NO_ACTUAL = DC_LANE.FROM_LOCATION_NBR
            AND RPOS.DC_NBR = DC_LANE.TO_LOCATION_NBR
) AS T1

WHERE
    IDC_DATE_ACTUAL_NEW >= (SELECT CALENDAR_DATE FROM UTIL.REC_START_DATE)
    AND IDC_DATE_ACTUAL_NEW <= (
        SELECT MAX(CALENDAR_DATE)
        FROM CALENDAR_DIM AS C1
            INNER JOIN (
                SELECT YEAR_WK_NBR
                FROM CALENDAR_DIM
                WHERE CALENDAR_DATE = DATE - 3
            ) AS C2
            ON C2.YEAR_WK_NBR = C1.YEAR_WK_NBR
    )

GROUP BY
    PART_NO, PO_NBR, PO_TYPE, CHANNEL_MTHD_CD, CHANNEL_MTHD_DESC,
    EVENT_CODE, EVENT_CODE_DESC, ORDER_DATE,
    COALESCE(SHIP_DATE_ACTUAL, SHIP_DATE_EXPECTED),
    STORE_DATE_PLANNED, STORE_DATE_EXPECTED, CLOSE_DATE, RDC_DATE_PLANNED,
    ORIG_PORT_DATE, PORT_DATE_PLANNED, PORT_DATE_EXPECTED, PORT_DATE_ACTUAL,
    IDC_DATE_PLANNED, FROM_LOCATION_NO, VENDOR_NAME,
    TO_LOCATION_NO_ACTUAL, TO_LOCATION_NO_PLANNED,
    ITEM_NBR, MDS_FAM_ID, ACCTG_DEPT_NBR, ORDER_DEPT_NBR, DEPT_CATEGORY_NBR,
    FROM_LOCATION_TYPE, TO_LOCATION_TYPE, IDC_DATE_ACTUAL_NEW
;
