SELECT
  BD.*,
  -- Daily actual count
  COUNT(DISTINCT LOAD_ID) OVER (
    PARTITION BY STORE_NBR, PROJECTED_DATE
  ) AS DAILY_ACTUAL,

  -- Weekly rollup
  WKLY.WEEKLY_PLAN,
  WKLY.WEEKLY_FORECAST,
  WKLY.WEEKLY_ACTUAL,

  -- Compliance classification
  CASE
    WHEN PROJECTED_DATE > CURRENT_DATE THEN NULL
    WHEN DAILY_ACTUAL > DAILY_PLAN     THEN 'OVER'
    WHEN DAILY_ACTUAL < DAILY_PLAN     THEN 'UNDER'
    ELSE 'COMPLIANT'
  END AS PLAN_COMPLIANCE_FLAG,

  -- Trailer utilization bucketing
  CASE
    WHEN CUBE_QTY       > 4050 THEN 'INVALID'
    WHEN TRLR_UTIL_PCT <= 0.25 THEN '0-25%'
    WHEN TRLR_UTIL_PCT <= 0.50 THEN '25-50%'
    WHEN TRLR_UTIL_PCT <= 0.75 THEN '50-75%'
    WHEN TRLR_UTIL_PCT <= 0.85 THEN '75-85%'
    ELSE 'FULL (85%+)'
  END AS UTILIZATION_BUCKET

FROM base_data BD
  LEFT JOIN (
    SELECT
      STORE_NBR,
      YEAR_WK_NBR,
      SUM(DAILY_PLAN)           AS WEEKLY_PLAN,
      SUM(FORECAST)             AS WEEKLY_FORECAST,
      COUNT(DISTINCT LOAD_ID)   AS WEEKLY_ACTUAL
    FROM daily_rollup
    GROUP BY STORE_NBR, YEAR_WK_NBR
  ) AS WKLY
    ON BD.STORE_NBR     = WKLY.STORE_NBR
   AND BD.YEAR_WK_NBR  = WKLY.YEAR_WK_NBR;
