/*
OWNER: Supply Chain Flow Planning Team
PURPOSE: End-to-end trailer planning pipeline with forecasting, carryover analysis, and compliance attribution
FEATURES: 
  - Multi-stage DDL pipeline (CREATE OR REPLACE TABLE)
  - Complex nested CTEs with 10+ levels
  - Window functions (LAG, LEAD, PARTITION BY, ROWS BETWEEN)
  - MERGE statements for incremental updates
  - DELETE statements with correlated subqueries
  - Custom TEMP FUNCTION for business logic encapsulation
  - Dashboard table generation with rollup calculations
PLATFORM: Google BigQuery
*/

/* -------------- STAGE 1: UPDATE TRAILER PLAN FORECAST -------------- */
/*
  PROVIDES MOST RECENT VERSIONS OF THE STORE INBOUND TRAILER FORECAST AND PLAN
  - INCLUDES ALL CALENDAR DATES AND LOCATIONS WITHIN THE FORECAST DATE RANGE
  - LOGIC IS APPLIED TO RETRIEVE THE MOST RECENT VALUES WHEN DATA IS MISSING
*/
CREATE OR REPLACE TABLE `flow-analytics-prod.flow_planning.delivery_forecast_current` AS (
  WITH
  
  BASE_DATA AS (
    SELECT
      COALESCE(CAP.RUN_DATETIME, CURRENT_DATETIME) AS RUN_DATETIME,
      RNG.LOCATION_ID,
      COALESCE(
        CAP.DELIVERY_TYPE_CODE,
        LAST_VALUE(CAP.DELIVERY_TYPE_CODE IGNORE NULLS) OVER (
          PARTITION BY RNG.LOCATION_ID 
          ORDER BY CAL.CALENDAR_DATE ASC 
          ROWS UNBOUNDED PRECEDING
        )
      ) AS DELIVERY_TYPE_CODE,
      CAL.CALENDAR_DATE AS CAP_CALENDAR_DATE,
      CAL.YEAR_WK_NBR AS CAP_YEAR_WK_NBR,
      CAL.YEAR_NBR AS CAP_YEAR_NBR,
      CAL.WEEK_NBR AS CAP_WEEK_NBR,
      CAL.WEEK_DAY_NAME AS CAP_WEEK_DAY_NAME,
      CAL2.CALENDAR_DATE AS DEL_CALENDAR_DATE,
      CAL2.YEAR_WK_NBR AS DEL_YEAR_WK_NBR,
      
      -- Forward-fill daily plan from previous same-day-of-week
      COALESCE(
        CAP.DAILY_CAP,
        LAST_VALUE(CAP.DAILY_CAP IGNORE NULLS) OVER (
          PARTITION BY RNG.LOCATION_ID, EXTRACT(DAYOFWEEK FROM CAL.CALENDAR_DATE) 
          ORDER BY CAL.CALENDAR_DATE ASC 
          ROWS UNBOUNDED PRECEDING
        )
      ) AS DAILY_PLAN,
      
      IF(
        COALESCE(
          CAP.DAILY_CAP,
          LAST_VALUE(CAP.DAILY_CAP IGNORE NULLS) OVER (
            PARTITION BY RNG.LOCATION_ID, EXTRACT(DAYOFWEEK FROM CAL.CALENDAR_DATE) 
            ORDER BY CAL.CALENDAR_DATE ASC 
            ROWS UNBOUNDED PRECEDING
          )
        ) > 0, 1, 0
      ) AS DAILY_FLAG
      
    FROM `enterprise-dw.calendar_dims.calendar_dim` AS CAL,
      (
        SELECT
          LOCATION_ID,
          MIN(CAP_CALENDAR_DATE) AS CAP_FORECAST_START_DATE,
          MAX(CAP_CALENDAR_DATE) AS CAP_FORECAST_END_DATE
        FROM `flow-analytics-dev.flow_planning.delivery_forecast_adjusted`
        GROUP BY LOCATION_ID
      ) AS RNG
      
      LEFT JOIN (
        SELECT DISTINCT *
        FROM `flow-analytics-dev.flow_planning.delivery_forecast_adjusted`
        QUALIFY RUN_DATETIME = MAX(RUN_DATETIME) OVER (PARTITION BY LOCATION_ID, CAP_CALENDAR_DATE)
      ) AS CAP
        ON CAL.CALENDAR_DATE = CAP.CAP_CALENDAR_DATE
        AND RNG.LOCATION_ID = CAP.LOCATION_ID
      
      INNER JOIN `enterprise-dw.calendar_dims.calendar_dim` AS CAL2
        ON CAL.CALENDAR_DATE = CAL2.CALENDAR_DATE - 7  -- Delivery offset
        
    WHERE CAL.CALENDAR_DATE BETWEEN CAP_FORECAST_START_DATE AND CAP_FORECAST_END_DATE
  )

  SELECT
    BASE_DATA.*,
    -- Must-ship flag: days adjacent to zero-plan days
    CASE
      WHEN DAILY_PLAN = 0 THEN 'N'
      WHEN MIN(DAILY_PLAN) OVER (
        PARTITION BY LOCATION_ID 
        ORDER BY CAP_CALENDAR_DATE ASC 
        ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING
      ) = 0 THEN 'Y'
      ELSE 'N'
    END AS MUST_SHIP_FLAG
  FROM BASE_DATA 
  ORDER BY LOCATION_ID, CAP_CALENDAR_DATE
);


/* -------------- STAGE 2: CREATE LOAD LIST FROM LEGACY TMS -------------- */
CREATE OR REPLACE TABLE `flow-analytics-dev.staging.trailer_plan_legacy_loads` AS (
  WITH

  EST_READY AS (
    -- Estimated ready timestamp when load was created
    SELECT
      L.LOAD_ID,
      L.TRAILER_ID,
      L.CREATE_TS_UTC,
      L.READY_TS_UTC,
      L.LAST_CHANGE_TS_UTC
    FROM `supply-chain-dw.tms.load_update_history` AS L
    WHERE
      L.LOAD_STATUS NOT IN ('CANCEL')
      AND TRIM(L.FREIGHT_CATEGORY_CODE) = 'STR'
      AND L.TRAILER_ID IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY LOAD_ID, CREATE_TS_UTC ORDER BY LAST_CHANGE_TS_UTC ASC) = 1
  ),
  
  FIRST_READY AS (
    -- First ready timestamp after trailer is assigned
    SELECT
      L.LOAD_ID,
      L.TRAILER_ID,
      L.CREATE_TS_UTC,
      L.READY_TS_UTC,
      L.LAST_CHANGE_TS_UTC
    FROM `supply-chain-dw.tms.load_update_history` AS L
    WHERE
      L.LOAD_STATUS NOT IN ('CANCEL')
      AND TRIM(L.FREIGHT_CATEGORY_CODE) = 'STR'
      AND L.TRAILER_ID IS NOT NULL
      AND UPPER(TRIM(L.TRAILER_ID)) NOT LIKE '%P-%'  -- Exclude placeholder trailers
    QUALIFY ROW_NUMBER() OVER (PARTITION BY LOAD_ID, CREATE_TS_UTC ORDER BY LAST_CHANGE_TS_UTC ASC) = 1
  )

  SELECT DISTINCT
    L.LOAD_ID,
    T.TRIP_ID,
    TRIM(L.TRAILER_ID) AS TRAILER_ID,
    L.ORIGIN_LOCATION_ID,
    L.DEST_LOCATION_ID,
    L.LOAD_STATUS,
    T.TRIP_STATUS_CODE,
    DATE(T.PROJECTED_TS) AS PROJECTED_DATE,
    EXTRACT(HOUR FROM T.PROJECTED_TS) AS DELIVERY_SLOT,
    DATETIME(EST.READY_TS_UTC, TZ.TIME_ZONE_NAME) AS EST_READY_TS,
    DATETIME(FIRST.READY_TS_UTC, TZ.TIME_ZONE_NAME) AS ORIG_READY_TS,
    DATETIME(L.READY_TS_UTC, TZ.TIME_ZONE_NAME) AS CUR_READY_TS,
    DATETIME(FIRST.LAST_CHANGE_TS_UTC, TZ.TIME_ZONE_NAME) AS ADJ_READY_TS,
    
    -- Intelligent ready timestamp selection
    DATETIME(IF(
      UPPER(TRIM(L.TRAILER_ID)) NOT LIKE '%P-%',
      CASE
        WHEN ABS(DATETIME_DIFF(EST.READY_TS_UTC, L.READY_TS_UTC, SECOND)) <= 2 
        THEN GREATEST(L.READY_TS_UTC, FIRST.LAST_CHANGE_TS_UTC)
        ELSE L.READY_TS_UTC
      END,
      NULL
    ), TZ.TIME_ZONE_NAME) AS READY_TS,
    
    T.PROJECTED_TS,
    CASE WHEN T.DEPART_ODOM_MILE > 0 THEN DATETIME(T.DEPART_TS_UTC, TZ.TIME_ZONE_NAME) END AS DEPART_TS
    
  FROM `supply-chain-dw.tms.trip_load_xref` AS TL
    INNER JOIN `supply-chain-dw.tms.loads` AS L
      ON TL.LOAD_ID = L.LOAD_ID
    INNER JOIN `supply-chain-dw.tms.trips` AS T
      ON TL.TRIP_ID = T.TRIP_ID
    INNER JOIN `enterprise-dw.location_dims.dc_dim` AS D
      ON L.ORIGIN_LOCATION_ID = D.DC_NBR
      AND D.COUNTRY_CODE = 'US'
      AND D.CURRENT_IND = 'Y'
    LEFT JOIN (
      SELECT
        DC_NBR,
        GET_TIMEZONE_NAME(TIME_ZONE_CODE) AS TIME_ZONE_NAME
      FROM `enterprise-dw.location_dims.dc_dim`
      WHERE COUNTRY_CODE = 'US' AND CURRENT_IND = 'Y'
    ) AS TZ
      ON D.DC_NBR = TZ.DC_NBR
    INNER JOIN `enterprise-dw.location_dims.store_dim` AS SD
      ON L.DEST_LOCATION_ID = SD.STORE_NBR
      AND SD.COUNTRY_CODE = 'US'
      AND SD.STATE_PROV_CODE NOT IN ('AK', 'HI', 'PR')  -- Continental US
    LEFT JOIN EST_READY AS EST
      ON L.LOAD_ID = EST.LOAD_ID
      AND L.CREATE_TS_UTC = EST.CREATE_TS_UTC
    LEFT JOIN FIRST_READY AS FIRST
      ON L.LOAD_ID = FIRST.LOAD_ID
      AND L.CREATE_TS_UTC = FIRST.CREATE_TS_UTC
      
  WHERE
    T.PROJECTED_TS IS NOT NULL
    AND DATE(T.PROJECTED_TS) >= CURRENT_DATE - 420
    AND L.TRAILER_ID IS NOT NULL
    AND (DATE(T.PROJECTED_TS) >= CURRENT_DATE OR UPPER(TRIM(L.TRAILER_ID)) NOT LIKE '%P-%')
    AND UPPER(TRIM(L.TRAILER_ID)) NOT LIKE '%DUMMY%'
    AND TRIM(T.TRIP_TYPE_CODE) IN ('STORE', 'CONSOLIDATED')
    AND TRIM(L.FREIGHT_CATEGORY_CODE) = 'STR'
    AND TRIM(L.LOAD_STATUS) NOT IN ('CANCEL')
    AND TRIM(T.TRIP_STATUS_CODE) NOT IN ('CANCEL')
    AND D.DC_TYPE_DESC = 'Regional'
);


/* -------------- STAGE 3: PULL DOOR OPEN/CLOSE TIMESTAMPS -------------- */
CREATE OR REPLACE TABLE `flow-analytics-dev.staging.trailer_plan_door_timestamps` AS (
  WITH
  
  TRIP_LIST AS (
    SELECT DISTINCT TRIP_ID, GATE_OUT_DESTINATIONS
    FROM `supply-chain-dw.yard_management.trailer_operations` AS TRLR_OPS
      INNER JOIN `enterprise-dw.location_dims.store_dim` AS SD
        ON TRLR_OPS.GATE_OUT_DESTINATIONS = CAST(SD.STORE_NBR AS STRING)
        AND SD.COUNTRY_CODE = 'US'
        AND SD.CURRENT_IND = 'Y'
    WHERE
      OPERATION_TYPE = 'TRAILER_GATE_OUT'
      AND DATE(ENTITY_OPERATION_TS) >= CURRENT_DATE - 420
      AND TRIM(UPPER(CARRIER_ID)) IN ('INTERNAL', 'CARRIER_A', 'CARRIER_B')
  ),

  ACTIVITY AS (
    SELECT
      CAST(ACTV.DC_NUMBER AS INT64) AS DC_NBR,
      SAFE_CAST(TRP.GATE_OUT_DESTINATIONS AS INT64) AS STORE_NBR,
      ACTV.TRIP_ID,
      ACTV.TRAILER_ID,
      COUNT(DISTINCT DATETIME(IF(ACTV.OPERATION_TYPE = 'OUTBOUND_TRAILER_DOOR_OPEN', ACTV.ENTITY_OPERATION_TS, NULL))) AS DOOR_OPEN_COUNT,
      MIN(DATETIME(IF(ACTV.OPERATION_TYPE IN ('TRAILER_GATE_IN', 'OUTBOUND_TRAILER_DOOR_OPEN'), ACTV.ENTITY_OPERATION_TS, NULL))) AS GATE_IN_TS,
      MIN(DATETIME(IF(ACTV.OPERATION_TYPE = 'OUTBOUND_TRAILER_DOOR_OPEN', ACTV.ENTITY_OPERATION_TS, NULL))) AS FIRST_TRAILER_DOOR_OPEN_TS,
      MAX(DATETIME(IF(ACTV.OPERATION_TYPE = 'OUTBOUND_TRAILER_DOOR_CLOSE', ACTV.ENTITY_OPERATION_TS, NULL))) AS LAST_TRAILER_DOOR_CLOSE_TS,
      MAX(DATETIME(IF(ACTV.OPERATION_TYPE IN ('TRAILER_GATE_OUT', 'OUTBOUND_TRAILER_DOOR_CLOSE'), ACTV.ENTITY_OPERATION_TS, NULL))) AS GATE_OUT_TS
    FROM `supply-chain-dw.yard_management.trailer_operations` AS ACTV
      INNER JOIN TRIP_LIST AS TRP
        ON ACTV.TRIP_ID = TRP.TRIP_ID
    WHERE ACTV.OPERATION_TYPE IN (
      'TRAILER_GATE_IN', 'OUTBOUND_TRAILER_DOOR_OPEN',
      'OUTBOUND_TRAILER_DOOR_CLOSE', 'TRAILER_GATE_OUT'
    )
    GROUP BY DC_NBR, STORE_NBR, TRIP_ID, TRAILER_ID
  )

  SELECT
    DC_NBR, STORE_NBR, TRIP_ID, TRAILER_ID,
    MAX(DOOR_OPEN_COUNT) AS DOOR_OPEN_COUNT,
    MIN(GATE_IN_TS) AS GATE_IN_TS,
    MIN(FIRST_TRAILER_DOOR_OPEN_TS) AS FIRST_TRAILER_DOOR_OPEN_TS,
    MAX(LAST_TRAILER_DOOR_CLOSE_TS) AS LAST_TRAILER_DOOR_CLOSE_TS,
    MAX(GATE_OUT_TS) AS GATE_OUT_TS
  FROM (
    SELECT
      DC_NBR, STORE_NBR, TRIP_ID, TRAILER_ID, DOOR_OPEN_COUNT,
      -- Handle missing gate timestamps with adjacent activity
      IF(
        COALESCE(FIRST_TRAILER_DOOR_OPEN_TS, LAST_TRAILER_DOOR_CLOSE_TS) IS NOT NULL,
        COALESCE(GATE_IN_TS, DATE_ADD(LAG(GATE_OUT_TS, 1) OVER (PARTITION BY DC_NBR, TRAILER_ID ORDER BY GATE_OUT_TS), INTERVAL 1 MINUTE)),
        NULL
      ) AS GATE_IN_TS,
      FIRST_TRAILER_DOOR_OPEN_TS,
      LAST_TRAILER_DOOR_CLOSE_TS,
      IF(
        COALESCE(FIRST_TRAILER_DOOR_OPEN_TS, LAST_TRAILER_DOOR_CLOSE_TS) IS NOT NULL,
        COALESCE(GATE_OUT_TS, DATE_SUB(LEAD(GATE_IN_TS, 1) OVER (PARTITION BY DC_NBR, TRAILER_ID ORDER BY GATE_IN_TS), INTERVAL 1 MINUTE)),
        NULL
      ) AS GATE_OUT_TS
    FROM ACTIVITY
    WHERE COALESCE(FIRST_TRAILER_DOOR_OPEN_TS, LAST_TRAILER_DOOR_CLOSE_TS, GATE_OUT_TS) IS NOT NULL
  )
  GROUP BY DC_NBR, STORE_NBR, TRIP_ID, TRAILER_ID
);


/* -------------- STAGE 4: ADD LOAD ACTIVITY FROM MULTIPLE SOURCES -------------- */
CREATE OR REPLACE TABLE `flow-analytics-dev.staging.trailer_plan_activity` AS (
  WITH
  
  -- Source 1: Load Status Stop (most reliable)
  LOAD_STAT_DEPART AS (
    SELECT
      SAFE_CAST(LOAD_ID AS INT64) AS LOAD_ID,
      LOCATION_ID AS ORIG_LOC_ID,
      MIN(STATUS_TS_UTC) AS ORIG_DEPART_TS_UTC
    FROM `supply-chain-dw.tms.load_status_stop`
    WHERE TRIM(SHIP_STATUS_CODE) = 'AF' AND TRIM(LOCATION_TYPE_CODE) = 'DC'
    GROUP BY 1, 2
  ),

  LOAD_STAT_ARRIVE AS (
    SELECT
      SAFE_CAST(LOAD_ID AS INT64) AS LOAD_ID,
      LOCATION_ID AS DEST_LOC_ID,
      MIN(STATUS_TS_UTC) AS DEST_ARRIVAL_TS_UTC
    FROM `supply-chain-dw.tms.load_status_stop`
    WHERE TRIM(SHIP_STATUS_CODE) = 'X1' AND TRIM(LOCATION_TYPE_CODE) = 'STORE'
    GROUP BY 1, 2
  ),

  -- Source 2: Load Consolidated
  LOAD_CNSLD AS (
    SELECT
      LOAD_ID,
      TRIM(TRAILER_ID) AS TRAILER_ID,
      ORIGIN_LOC_ID,
      DEST_LOC_ID,
      LOAD_STATUS,
      DATETIME(LOAD_READY_TS) AS LOAD_READY_TS,
      DATETIME(ACTUAL_DELIVERY_TS) AS ACTUAL_DELIVERY_TS
    FROM `supply-chain-dw.consolidated.sc_load_consolidated`
    WHERE
      LOAD_STATUS NOT IN ('CANCEL')
      AND TRIM(FREIGHT_CATEGORY_CODE) = 'STR'
      AND TRIM(DEST_LOC_TYPE_CODE) = 'STORE'
      AND LOAD_READY_DATE > CURRENT_DATE - 365
  ),

  -- Source 3: Trip Movement
  TRIP_MOVEMENT AS (
    SELECT
      TRIP_ID, LOAD_ID, TRIM(TRAILER_ID) AS TRAILER_ID,
      ORIGIN_LOC_ID, DEST_LOC_ID,
      MAX(TRANSIT_MINUTE_QTY) AS TRANSIT_MINUTE_QTY,
      MAX(ESTIMATED_ORIG_DEPART_TS_UTC) AS ESTIMATED_ORIG_DEPART_TS_UTC,
      MAX(ACTUAL_ORIG_DEPART_TS_UTC) AS ACTUAL_ORIG_DEPART_TS_UTC,
      MAX(ACTUAL_DEST_ARRIVAL_TS_UTC) AS ACTUAL_DEST_ARRIVAL_TS_UTC
    FROM `supply-chain-dw.tms.trip_movement`
    GROUP BY TRIP_ID, LOAD_ID, TRIM(TRAILER_ID), ORIGIN_LOC_ID, DEST_LOC_ID
  ),

  FINAL AS (
    SELECT DISTINCT
      L.LOAD_ID, L.TRIP_ID, L.TRAILER_ID,
      L.ORIGIN_LOCATION_ID AS ORIG_LOC_ID,
      L.DEST_LOCATION_ID AS DEST_LOC_ID,
      L.LOAD_STATUS,
      L.TRIP_STATUS_CODE,
      L.PROJECTED_DATE,
      L.DELIVERY_SLOT,
      L.ORIG_READY_TS,
      
      -- Intelligent ready timestamp selection
      CASE
        WHEN L.READY_TS < OPN.LAST_TRAILER_DOOR_CLOSE_TS AND L.ADJ_READY_TS > OPN.LAST_TRAILER_DOOR_CLOSE_TS 
        THEN L.ADJ_READY_TS
        WHEN L.READY_TS < OPN.LAST_TRAILER_DOOR_CLOSE_TS AND L.ADJ_READY_TS < OPN.LAST_TRAILER_DOOR_CLOSE_TS 
        THEN OPN.LAST_TRAILER_DOOR_CLOSE_TS
        ELSE L.READY_TS
      END AS READY_TS,
      
      L.PROJECTED_TS,
      OPN.DOOR_OPEN_COUNT,
      OPN.FIRST_TRAILER_DOOR_OPEN_TS,
      OPN.LAST_TRAILER_DOOR_CLOSE_TS,
      OPN.GATE_OUT_TS,
      
      -- Coalesce departure from multiple sources (priority order)
      DATETIME_TRUNC(COALESCE(
        DATETIME(LSD.ORIG_DEPART_TS_UTC, TZ.TIME_ZONE_NAME),
        DATETIME(TM.ACTUAL_ORIG_DEPART_TS_UTC, TZ.TIME_ZONE_NAME),
        L.DEPART_TS
      ), SECOND) AS BEGIN_TRIP_TS,
      
      CASE
        WHEN LSD.ORIG_DEPART_TS_UTC IS NOT NULL THEN 'load_status_stop'
        WHEN TM.ACTUAL_ORIG_DEPART_TS_UTC IS NOT NULL THEN 'trip_movement'
        WHEN L.DEPART_TS IS NOT NULL THEN 'trip_table'
      END AS BEGIN_TRIP_SRC,
      
      -- Coalesce arrival from multiple sources (priority order)
      DATETIME_TRUNC(COALESCE(
        DATETIME(LSA.DEST_ARRIVAL_TS_UTC, TZ.TIME_ZONE_NAME),
        LC.ACTUAL_DELIVERY_TS,
        DATETIME(TM.ACTUAL_DEST_ARRIVAL_TS_UTC, TZ.TIME_ZONE_NAME)
      ), SECOND) AS END_TRIP_TS,
      
      CASE
        WHEN LSA.DEST_ARRIVAL_TS_UTC IS NOT NULL THEN 'load_status_stop'
        WHEN LC.ACTUAL_DELIVERY_TS IS NOT NULL THEN 'load_consolidated'
        WHEN TM.ACTUAL_DEST_ARRIVAL_TS_UTC IS NOT NULL THEN 'trip_movement'
      END AS END_TRIP_SRC
      
    FROM `flow-analytics-dev.staging.trailer_plan_legacy_loads` AS L
      LEFT JOIN (
        SELECT DC_NBR, GET_TIMEZONE_NAME(TIME_ZONE_CODE) AS TIME_ZONE_NAME
        FROM `enterprise-dw.location_dims.dc_dim`
        WHERE COUNTRY_CODE = 'US' AND CURRENT_IND = 'Y'
      ) AS TZ
        ON L.ORIGIN_LOCATION_ID = TZ.DC_NBR
      LEFT JOIN LOAD_STAT_DEPART AS LSD
        ON L.LOAD_ID = LSD.LOAD_ID AND L.ORIGIN_LOCATION_ID = LSD.ORIG_LOC_ID
      LEFT JOIN LOAD_STAT_ARRIVE AS LSA
        ON L.LOAD_ID = LSA.LOAD_ID AND L.DEST_LOCATION_ID = LSA.DEST_LOC_ID
      LEFT JOIN LOAD_CNSLD AS LC
        ON L.LOAD_ID = LC.LOAD_ID AND L.DEST_LOCATION_ID = LC.DEST_LOC_ID
        AND TRIM(L.TRAILER_ID) = TRIM(LC.TRAILER_ID)
      LEFT JOIN TRIP_MOVEMENT AS TM
        ON L.LOAD_ID = TM.LOAD_ID AND L.TRIP_ID = TM.TRIP_ID
        AND L.TRAILER_ID = TM.TRAILER_ID
      LEFT JOIN `flow-analytics-dev.staging.trailer_plan_door_timestamps` AS OPN
        ON L.ORIGIN_LOCATION_ID = OPN.DC_NBR AND L.TRAILER_ID = OPN.TRAILER_ID
        AND (
          (L.READY_TS >= GREATEST(OPN.GATE_IN_TS, COALESCE(FIRST_TRAILER_DOOR_OPEN_TS, LAST_TRAILER_DOOR_CLOSE_TS))
           AND OPN.GATE_OUT_TS BETWEEN L.READY_TS AND DATETIME_ADD(L.READY_TS, INTERVAL 3 DAY))
          OR (L.READY_TS BETWEEN GREATEST(OPN.GATE_IN_TS, COALESCE(FIRST_TRAILER_DOOR_OPEN_TS, LAST_TRAILER_DOOR_CLOSE_TS)) 
              AND DATETIME_ADD(GREATEST(OPN.GATE_IN_TS, COALESCE(FIRST_TRAILER_DOOR_OPEN_TS, LAST_TRAILER_DOOR_CLOSE_TS)), INTERVAL 5 DAY)
              AND OPN.GATE_OUT_TS IS NULL)
        )
  )

  SELECT * EXCEPT(ADJ_READY_TS) FROM FINAL QUALIFY COUNT(LOAD_ID) OVER (PARTITION BY LOAD_ID, DATE(PROJECTED_TS)) = 1
);


/* -------------- STAGE 5: ADD VOLUME FROM INVOICES -------------- */
CREATE OR REPLACE TABLE `flow-analytics-dev.staging.trailer_plan_quantities` AS (
  WITH
  
  LOADS AS (
    SELECT
      COALESCE(MODERN.LOAD_ID, LEGACY.LOAD_ID) AS LOAD_ID,
      COALESCE(MODERN.TRIP_ID, LEGACY.TRIP_ID) AS TRIP_ID,
      COALESCE(MODERN.TRAILER_ID, LEGACY.TRAILER_ID) AS TRAILER_ID,
      COALESCE(MODERN.ORIG_LOC_ID, LEGACY.ORIG_LOC_ID) AS ORIG_LOC_ID,
      COALESCE(MODERN.DEST_LOC_ID, LEGACY.DEST_LOC_ID) AS DEST_LOC_ID,
      COALESCE(MODERN.LOAD_STATUS, LEGACY.LOAD_STATUS) AS LOAD_STATUS,
      COALESCE(MODERN.PROJECTED_DATE, LEGACY.PROJECTED_DATE) AS PROJECTED_DATE,
      COALESCE(MODERN.DELIVERY_SLOT, LEGACY.DELIVERY_SLOT) AS DELIVERY_SLOT,
      COALESCE(MODERN.READY_TS, LEGACY.READY_TS) AS READY_TS,
      COALESCE(MODERN.PROJECTED_TS, LEGACY.PROJECTED_TS) AS PROJECTED_TS,
      COALESCE(MODERN.DOOR_OPEN_COUNT, LEGACY.DOOR_OPEN_COUNT) AS DOOR_OPEN_COUNT,
      COALESCE(MODERN.FIRST_TRAILER_DOOR_OPEN_TS, LEGACY.FIRST_TRAILER_DOOR_OPEN_TS) AS FIRST_TRAILER_DOOR_OPEN_TS,
      COALESCE(MODERN.LAST_TRAILER_DOOR_CLOSE_TS, LEGACY.LAST_TRAILER_DOOR_CLOSE_TS) AS LAST_TRAILER_DOOR_CLOSE_TS,
      COALESCE(MODERN.BEGIN_TRIP_TS, LEGACY.BEGIN_TRIP_TS) AS BEGIN_TRIP_TS,
      COALESCE(MODERN.END_TRIP_TS, LEGACY.END_TRIP_TS) AS END_TRIP_TS
    FROM `flow-analytics-dev.staging.trailer_plan_modern_tms` AS MODERN
      FULL JOIN `flow-analytics-dev.staging.trailer_plan_activity` AS LEGACY
        ON MODERN.ORIG_LOC_ID = LEGACY.ORIG_LOC_ID
        AND MODERN.DEST_LOC_ID = LEGACY.DEST_LOC_ID
        AND MODERN.TRAILER_ID = LEGACY.TRAILER_ID
        AND MODERN.PROJECTED_DATE = LEGACY.PROJECTED_DATE
  ),

  INVOICE_LINE AS (
    SELECT
      DCL.INVOICE_NBR,
      DCL.INVOICE_DATE,
      SUM(DCL.TOT_WHPK_SHIP_QTY) AS TOT_WHPK_SHIP_QTY,
      
      -- Non-breakpack case quantity
      SUM(CASE
        WHEN PCK.PACK_TYPE IN ('CASEPACK', 'FULL_PALLET', 'MIXED_PALLET') THEN DCL.TOT_WHPK_SHIP_QTY
        WHEN DCL.LABEL_TYPE_CODE IN ('FDSC') 
          AND ITM.WHPK_LENGTH_QTY + ITM.WHPK_WIDTH_QTY + ITM.WHPK_HEIGHT_QTY > 52 
        THEN DCL.TOT_WHPK_SHIP_QTY
        ELSE 0
      END) AS NON_BRPK_CASE_QTY,
      
      -- Total cube
      SUM(LEAST(
        COALESCE(
          DCL.TOT_WHPK_SHIP_QTY * ITM.WHPK_CUBE_QTY,
          ((DCL.TOT_WHPK_SHIP_QTY * ITM.WHPK_QTY) / ITM.VNPK_QTY) * ITM.VNPK_CUBE_QTY
        ),
        ((DCL.TOT_WHPK_SHIP_QTY * ITM.WHPK_QTY) / ITM.VNPK_QTY) * ITM.VNPK_CUBE_QTY
      )) AS CUBE_QTY,
      
      -- Total weight
      SUM(LEAST(
        COALESCE(
          DCL.TOT_WHPK_SHIP_QTY * ITM.WHPK_WEIGHT_QTY,
          ((DCL.TOT_WHPK_SHIP_QTY * ITM.WHPK_QTY) / ITM.VNPK_QTY) * ITM.VNPK_WEIGHT_QTY
        ),
        ((DCL.TOT_WHPK_SHIP_QTY * ITM.WHPK_QTY) / ITM.VNPK_QTY) * ITM.VNPK_WEIGHT_QTY
      )) AS WEIGHT_QTY,
      
      -- Automated picking system cube
      SUM(IF(LEFT(TRIM(LABEL_TYPE_CODE), 3) = 'AUT', LEAST(
        COALESCE(
          DCL.TOT_WHPK_SHIP_QTY * ITM.WHPK_CUBE_QTY,
          ((DCL.TOT_WHPK_SHIP_QTY * ITM.WHPK_QTY) / ITM.VNPK_QTY) * ITM.VNPK_CUBE_QTY
        ),
        ((DCL.TOT_WHPK_SHIP_QTY * ITM.WHPK_QTY) / ITM.VNPK_QTY) * ITM.VNPK_CUBE_QTY
      ), 0)) AS AUTO_CUBE_QTY
      
    FROM `supply-chain-dw.dc_operations.invoice_line` AS DCL
      INNER JOIN `flow-analytics-prod.item_master.item_current_adj` AS ITM
        ON DCL.ITEM_NBR = ITM.MDS_FAM_ID
      LEFT JOIN `flow-analytics-prod.flow_planning.pick_code_class` AS PCK
        ON DCL.LABEL_TYPE_CODE = LEFT(PCK.PICK_TYPE_CODE, 4)
    WHERE
      DATE(DCL.INVOICE_DATE) >= CURRENT_DATE - 365
      AND OUTS_CODE NOT IN ('O', 'R', 'M', 'F')
    GROUP BY DCL.INVOICE_NBR, DCL.INVOICE_DATE
  ),

  INVOICE_SUM AS (
    SELECT
      DCI.LOAD_ID,
      DCI.TRIP_ID,
      TRIM(DCI.TRAILER_ID) AS TRAILER_ID,
      DCI.SHIP_FROM_DC_NBR,
      DCI.SHIP_TO_STORE_NBR,
      MIN(DCI.INVOICE_DATE) AS INVOICE_DATE,
      SUM(DCL.NON_BRPK_CASE_QTY + COALESCE(DCI.BREAKPACK_CASE_CNT, 0)) AS CASE_QTY,
      SUM(DCL.CUBE_QTY) AS CUBE_QTY,
      SUM(DCL.WEIGHT_QTY) AS WEIGHT_QTY,
      SUM(DCL.AUTO_CUBE_QTY) AS AUTO_CUBE_QTY,
      'INVOICE_LINE' AS SRC
    FROM `supply-chain-dw.dc_operations.invoice_header` AS DCI
      INNER JOIN INVOICE_LINE AS DCL
        ON DCI.INVOICE_NBR = DCL.INVOICE_NBR
        AND DCI.INVOICE_DATE = DCL.INVOICE_DATE
    GROUP BY 1, 2, 3, 4, 5
  )

  SELECT
    L.*,
    MAX(DC_INVC.INVOICE_DATE) AS INVOICE_DATE,
    SUM(CAST(DC_INVC.CASE_QTY AS INT64)) AS TOT_CASE_SHIP_QTY,
    SUM(DC_INVC.CUBE_QTY) AS TOT_CUBE_QTY,
    SUM(DC_INVC.WEIGHT_QTY) AS TOT_WEIGHT_QTY,
    SUM(DC_INVC.AUTO_CUBE_QTY) AS AUTO_CUBE_QTY
  FROM LOADS AS L
    LEFT JOIN INVOICE_SUM AS DC_INVC
      ON TRIM(L.TRAILER_ID) = TRIM(DC_INVC.TRAILER_ID)
      AND L.ORIG_LOC_ID = DC_INVC.SHIP_FROM_DC_NBR
      AND L.DEST_LOC_ID = DC_INVC.SHIP_TO_STORE_NBR
      AND (DC_INVC.INVOICE_DATE BETWEEN DATE(L.READY_TS) - 1 AND L.PROJECTED_DATE
           OR (L.LOAD_ID = DC_INVC.LOAD_ID AND L.TRIP_ID = DC_INVC.TRIP_ID))
  GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
);


/* -------------- STAGE 6: MERGE INTO PRODUCTION TABLE -------------- */
MERGE INTO `flow-analytics-prod.flow_planning.trailer_plan` AS TRGT
USING `flow-analytics-dev.staging.trailer_plan_staged` AS SRC
ON TRGT.LOAD_ID = SRC.LOAD_ID AND TRGT.RUN_DATE = SRC.RUN_DATE

WHEN MATCHED THEN
  UPDATE SET
    REFRESH_TIME = SRC.REFRESH_TIME,
    TRIP_ID = SRC.TRIP_ID,
    TRAILER_ID = SRC.TRAILER_ID,
    ORIG_LOC_ID = SRC.ORIG_LOC_ID,
    DEST_LOC_ID = SRC.DEST_LOC_ID,
    DELIVERY_SLOT = SRC.DELIVERY_SLOT,
    CASE_QTY = SRC.CASE_QTY,
    CUBE_QTY = SRC.CUBE_QTY,
    WEIGHT_QTY = SRC.WEIGHT_QTY,
    TRLR_UTIL_PCT = SRC.TRLR_UTIL_PCT,
    READY_TS = SRC.READY_TS,
    PROJECTED_TS = SRC.PROJECTED_TS,
    BEGIN_TRIP_TS = SRC.BEGIN_TRIP_TS,
    END_TRIP_TS = SRC.END_TRIP_TS,
    LOAD_STATUS = SRC.LOAD_STATUS,
    DAILY_PLAN = SRC.DAILY_PLAN,
    MUST_SHIP_FLAG = SRC.MUST_SHIP_FLAG,
    READY_FLAG = SRC.READY_FLAG,
    CARRY_OVER_FLAG = SRC.CARRY_OVER_FLAG,
    PULL_FORWARD_FLAG = SRC.PULL_FORWARD_FLAG,
    OVER_PLAN_FLAG = SRC.OVER_PLAN_FLAG,
    CAPPED_FLAG = SRC.CAPPED_FLAG

WHEN NOT MATCHED BY TARGET THEN
  INSERT (
    REFRESH_TIME, RUN_DATE, LOAD_ID, TRIP_ID, TRAILER_ID,
    ORIG_LOC_ID, DEST_LOC_ID, DELIVERY_SLOT,
    CASE_QTY, CUBE_QTY, WEIGHT_QTY, TRLR_UTIL_PCT,
    READY_TS, PROJECTED_TS, BEGIN_TRIP_TS, END_TRIP_TS,
    LOAD_STATUS, DAILY_PLAN, MUST_SHIP_FLAG,
    READY_FLAG, CARRY_OVER_FLAG, PULL_FORWARD_FLAG, OVER_PLAN_FLAG, CAPPED_FLAG
  )
  VALUES (
    SRC.REFRESH_TIME, SRC.RUN_DATE, SRC.LOAD_ID, SRC.TRIP_ID, SRC.TRAILER_ID,
    SRC.ORIG_LOC_ID, SRC.DEST_LOC_ID, SRC.DELIVERY_SLOT,
    SRC.CASE_QTY, SRC.CUBE_QTY, SRC.WEIGHT_QTY, SRC.TRLR_UTIL_PCT,
    SRC.READY_TS, SRC.PROJECTED_TS, SRC.BEGIN_TRIP_TS, SRC.END_TRIP_TS,
    SRC.LOAD_STATUS, SRC.DAILY_PLAN, SRC.MUST_SHIP_FLAG,
    SRC.READY_FLAG, SRC.CARRY_OVER_FLAG, SRC.PULL_FORWARD_FLAG, SRC.OVER_PLAN_FLAG, SRC.CAPPED_FLAG
  );


/* -------------- STAGE 7: DELETE CANCELLED LOADS -------------- */
DELETE `flow-analytics-prod.flow_planning.trailer_plan` AS TGT
WHERE EXISTS (
  SELECT 1 FROM `flow-analytics-dev.staging.cancelled_loads` AS DEL
  WHERE TGT.LOAD_ID = DEL.LOAD_ID
    AND TGT.ORIG_LOC_ID = DEL.ORIG_LOC_ID
    AND TGT.DEST_LOC_ID = DEL.DEST_LOC_ID
);


/* -------------- STAGE 8: ATTRIBUTION LOGIC FUNCTION -------------- */
-- Custom function for compliance attribution
CREATE TEMP FUNCTION COMPLIANCE_ATTRIBUTION(
  DAILY_PLAN INT64,
  DAILY_ACTL INT64,
  WEEKEND_PROTECTION_IND BOOLEAN,
  PREV_DAY_NOTICE_IND BOOLEAN,
  DAILY_AVAILABLE INT64,
  NEXT_DAY_AVAILABLE INT64,
  TRAILER_IDX INT64,
  MUST_SHIP_FLAG STRING,
  CARRY_OVER_COUNT INT64,
  NEXT_DAY_PLAN INT64,
  L7_UNDER_IND BOOLEAN,
  L7_TRLR_UTIL_PCT FLOAT64,
  L3W_INVENTORY_IND BOOLEAN,
  REQ_TYPE STRING,
  REQ_REASON STRING,
  LVL INT64
)
RETURNS STRING AS (
  CASE
    -- COMPLIANT - Excess Carry Overs - Weekend Protection
    WHEN DAILY_ACTL = DAILY_PLAN AND CARRY_OVER_COUNT > 1 AND WEEKEND_PROTECTION_IND = TRUE
    THEN CASE
      WHEN LVL = 3 THEN 'Excess Carry Overs - Weekend Protection'
      WHEN LVL = 4 THEN 'Trailer count matches plan with 2+ trailers carried over to protect the weekend'
      ELSE 'COMPLIANT'
    END
    
    -- COMPLIANT - Excess Carry Overs - 24HR Notice
    WHEN DAILY_ACTL = DAILY_PLAN AND CARRY_OVER_COUNT > 1 AND PREV_DAY_NOTICE_IND = TRUE
    THEN CASE
      WHEN LVL = 3 THEN 'Excess Carry Overs - 24-Hour Notice'
      WHEN LVL = 4 THEN 'Trailer count matches plan with 2+ trailers carried over due to 24-hour rule'
      ELSE 'COMPLIANT'
    END
    
    -- COMPLIANT
    WHEN DAILY_ACTL = DAILY_PLAN
    THEN CASE
      WHEN LVL = 3 THEN 'Compliant'
      WHEN LVL = 4 THEN 'Compliant'
      ELSE 'COMPLIANT'
    END

    -- UNDER - External Request - Trailer Was Available
    WHEN DAILY_ACTL < DAILY_PLAN AND DAILY_ACTL = 0 
      AND COALESCE(DAILY_AVAILABLE, 0) > 0 AND REQ_TYPE = 'UNDER'
    THEN CASE
      WHEN LVL = 1 THEN 'UNDER'
      WHEN LVL = 2 THEN 'EXTERNAL_REQUEST'
      WHEN LVL = 3 THEN REQ_REASON
      WHEN LVL = 4 THEN REQ_REASON
    END
    
    -- UNDER - Transportation - Trailer Was Available
    WHEN DAILY_ACTL < DAILY_PLAN AND DAILY_ACTL = 0 AND COALESCE(DAILY_AVAILABLE, 0) > 0
    THEN CASE
      WHEN LVL = 1 THEN 'UNDER'
      WHEN LVL = 2 THEN 'TRANSPORTATION'
      WHEN LVL = 3 THEN 'Guaranteed Delivery - Trailer Available'
      WHEN LVL = 4 THEN '1st trailer of a planned day was available but not sent'
    END
    
    -- UNDER - Must Ship - No Trailer Available
    WHEN DAILY_ACTL < DAILY_PLAN AND DAILY_ACTL = 0 
      AND COALESCE(DAILY_AVAILABLE, 0) = 0 AND MUST_SHIP_FLAG = 'Y'
    THEN CASE
      WHEN LVL = 1 THEN 'UNDER'
      WHEN LVL = 2 THEN 'TRANS_DC_HANDOFF'
      WHEN LVL = 3 THEN 'Must Ship - No Trailer Available'
      WHEN LVL = 4 THEN 'No trailer was available to send on a must ship date'
    END
    
    -- UNDER - Forecast Buffer Too High
    WHEN DAILY_ACTL < DAILY_PLAN AND DAILY_ACTL = 0 
      AND COALESCE(DAILY_AVAILABLE, 0) = 0 AND MUST_SHIP_FLAG = 'N' AND NEXT_DAY_AVAILABLE = 0
    THEN CASE
      WHEN LVL = 1 THEN 'UNDER'
      WHEN LVL = 2 THEN 'FORECAST'
      WHEN LVL = 3 THEN 'Forecast Buffer Too High'
      WHEN LVL = 4 THEN 'Too high of forecast buffers put in place'
    END

    -- OVER - Delivery On Non-Delivery Date
    WHEN DAILY_ACTL > DAILY_PLAN AND DAILY_PLAN = 0
    THEN CASE
      WHEN LVL = 1 THEN 'OVER'
      WHEN LVL = 2 THEN 'TRANSPORTATION'
      WHEN LVL = 3 THEN 'Delivery On Non-Delivery Date'
      WHEN LVL = 4 THEN 'A trailer was sent on an unplanned day'
    END
    
    -- OVER - Zero Carry Over
    WHEN DAILY_ACTL > DAILY_PLAN AND DAILY_PLAN > 0 
      AND CARRY_OVER_COUNT = 0 AND NEXT_DAY_PLAN > 0
    THEN CASE
      WHEN LVL = 1 THEN 'OVER'
      WHEN LVL = 2 THEN 'TRANSPORTATION'
      WHEN LVL = 3 THEN 'Zero Trailers Carried Over'
      WHEN LVL = 4 THEN 'A trailer was sent over plan when it could have been carried over'
    END
    
    -- OVER - Under/Over Pattern
    WHEN DAILY_ACTL > DAILY_PLAN AND DAILY_PLAN > 0 
      AND (CARRY_OVER_COUNT > 0 OR (CARRY_OVER_COUNT = 0 AND NEXT_DAY_PLAN = 0))
      AND L7_UNDER_IND = TRUE
    THEN CASE
      WHEN LVL = 1 THEN 'OVER'
      WHEN LVL = 2 THEN 'TRANS_DC_HANDOFF'
      WHEN LVL = 3 THEN 'Over Plan Day Caused By Under Plan Day'
      WHEN LVL = 4 THEN 'A trailer was sent over plan to make up for a previous under plan day'
    END
    
    -- OVER - Low Utilization
    WHEN DAILY_ACTL > DAILY_PLAN AND DAILY_PLAN > 0 
      AND (CARRY_OVER_COUNT > 0 OR (CARRY_OVER_COUNT = 0 AND NEXT_DAY_PLAN = 0))
      AND L7_UNDER_IND = FALSE AND L7_TRLR_UTIL_PCT < 0.75
    THEN CASE
      WHEN LVL = 1 THEN 'OVER'
      WHEN LVL = 2 THEN 'DC_OPS'
      WHEN LVL = 3 THEN 'Average Trailer Utilization Below 75%'
      WHEN LVL = 4 THEN 'An extra trailer was created due to low average utilization over last 7 days'
    END
    
    -- OVER - Forecast Too Low
    WHEN DAILY_ACTL > DAILY_PLAN AND DAILY_PLAN > 0 
      AND (CARRY_OVER_COUNT > 0 OR (CARRY_OVER_COUNT = 0 AND NEXT_DAY_PLAN = 0))
      AND L7_UNDER_IND = FALSE AND (L7_TRLR_UTIL_PCT >= 0.75 OR L7_TRLR_UTIL_PCT IS NULL)
    THEN CASE
      WHEN LVL = 1 THEN 'OVER'
      WHEN LVL = 2 THEN 'FORECAST'
      WHEN LVL = 3 THEN 'Forecasted Plan Was Too Low'
      WHEN LVL = 4 THEN 'Trailer volume forecasted was too low'
    END
  END
);


/* -------------- STAGE 9: BUILD DASHBOARD DATA -------------- */
CREATE OR REPLACE TABLE `flow-analytics-dev.flow_planning.trailer_plan_dashboard_base` AS (
  WITH
  
  BASE_DATA AS (
    SELECT
      RUN_DATE,
      IF(RUN_DATE = MAX(RUN_DATE) OVER (PARTITION BY LOAD_ID, TRIP_ID, TRIM(TRAILER_ID)), TRUE, FALSE) AS CURRENT_IND,
      ORIG_LOC_ID,
      DEST_LOC_ID,
      DATE(PROJECTED_TS) AS PROJECTED_DATE,
      MUST_SHIP_FLAG,
      LOAD_ID,
      TRIP_ID,
      TRIM(TRAILER_ID) AS TRAILER_ID,
      DATETIME_TRUNC(READY_TS, SECOND) AS READY_TS,
      DATETIME_TRUNC(PROJECTED_TS, SECOND) AS PROJECTED_TS,
      DATETIME_TRUNC(BEGIN_TRIP_TS, SECOND) AS BEGIN_TRIP_TS,
      DATETIME_TRUNC(END_TRIP_TS, SECOND) AS END_TRIP_TS,
      CASE_QTY,
      IF(CUBE_QTY > 4050, NULL, CUBE_QTY) AS CUBE_QTY,
      WEIGHT_QTY,
      IF(CUBE_QTY > 4050, NULL, TRLR_UTIL_PCT) AS TRLR_UTIL_PCT,
      CASE
        WHEN CUBE_QTY > 4050 THEN 'OTHER'
        WHEN TRLR_UTIL_PCT <= 0.25 THEN '0% - 25%'
        WHEN TRLR_UTIL_PCT <= 0.50 THEN '25% - 50%'
        WHEN TRLR_UTIL_PCT <= 0.75 THEN '50% - 75%'
        WHEN TRLR_UTIL_PCT <= 0.85 THEN '75% - 85%'
        WHEN TRLR_UTIL_PCT > 0.85 THEN 'FULL'
        ELSE 'OTHER'
      END AS TRLR_UTIL_PCT_GRP,
      READY_FLAG,
      CARRY_OVER_FLAG,
      PULL_FORWARD_FLAG,
      OVER_PLAN_FLAG,
      CASE
        WHEN CARRY_OVER_FLAG = TRUE AND OVER_PLAN_FLAG = TRUE THEN 'CARRY OVER - OVER CAP'
        WHEN PULL_FORWARD_FLAG = TRUE AND OVER_PLAN_FLAG = TRUE THEN 'PULL FORWARD - OVER CAP'
        WHEN CARRY_OVER_FLAG = TRUE THEN 'CARRY OVER'
        WHEN OVER_PLAN_FLAG = TRUE THEN 'OVER CAP'
        WHEN PULL_FORWARD_FLAG = TRUE THEN 'PULL FORWARD'
        WHEN END_TRIP_TS IS NOT NULL THEN 'DELIVERED'
        ELSE 'ON PROCESS'
      END AS TRAILER_STATUS
    FROM `flow-analytics-prod.flow_planning.trailer_plan`
    WHERE DATE_DIFFERENCE <= 60 OR DATE_DIFFERENCE IS NULL
  ),

  DAILY_ROLLUP AS (
    SELECT
      STORE_NBR,
      PROJECTED_DATE,
      PROJECTED_YEAR_WK_NBR,
      TRAILER_FCST,
      DAILY_PLAN,
      LEAD(DAILY_PLAN, 1) OVER (PARTITION BY STORE_NBR ORDER BY PROJECTED_DATE) AS NEXT_DAY_PLAN,
      TRAILER_COUNT,
      CARRY_OVER_COUNT
    FROM (
      SELECT
        STORE_NBR,
        PROJECTED_DATE,
        PROJECTED_YEAR_WK_NBR,
        COALESCE(TRAILER_FCST, 0) AS TRAILER_FCST,
        COALESCE(DAILY_PLAN, 0) AS DAILY_PLAN,
        COUNT(DISTINCT LOAD_ID) AS TRAILER_COUNT,
        COUNT(DISTINCT IF(CARRY_OVER_FLAG = TRUE, LOAD_ID, NULL)) AS CARRY_OVER_COUNT
      FROM BASE_DATA
      GROUP BY 1, 2, 3, 4, 5
    )
  ),

  WEEKLY_ROLLUP AS (
    SELECT
      STORE_NBR,
      PROJECTED_YEAR_WK_NBR,
      SUM(DAILY_PLAN) AS WEEKLY_PLAN,
      SUM(TRAILER_FCST) AS WEEKLY_FCST,
      SUM(TRAILER_COUNT) AS WEEKLY_ACTL
    FROM DAILY_ROLLUP
    GROUP BY STORE_NBR, PROJECTED_YEAR_WK_NBR
  )

  SELECT
    BD.*,
    DC.DC_NAME,
    DC.DC_REGION_NAME,
    DC.DC_SUB_TYPE_DESC,
    STR.CITY_NAME AS STORE_CITY,
    STR.STATE_PROV_CODE AS STORE_STATE,
    STR.REGION_NBR AS STORE_REGION_NBR,
    STR.REGION_NAME AS STORE_REGION_NAME,
    DLY.NEXT_DAY_PLAN,
    COALESCE(DLY.CARRY_OVER_COUNT, 0) AS TOTAL_CARRY_OVERS,
    WKLY.WEEKLY_FCST,
    WKLY.WEEKLY_PLAN,
    WKLY.WEEKLY_ACTL,
    COUNT(DISTINCT BD.LOAD_ID) OVER (PARTITION BY BD.STORE_NBR, BD.PROJECTED_DATE) AS DAILY_ACTL,
    
    -- Plan compliance flag
    CASE
      WHEN BD.PROJECTED_DATE > DATE(BD.REFRESH_TIME) THEN NULL
      WHEN COUNT(DISTINCT BD.LOAD_ID) OVER (PARTITION BY BD.STORE_NBR, BD.PROJECTED_DATE) 
        > MAX(BD.DAILY_PLAN) OVER (PARTITION BY BD.STORE_NBR, BD.PROJECTED_DATE) THEN 'OVER'
      WHEN COUNT(DISTINCT BD.LOAD_ID) OVER (PARTITION BY BD.STORE_NBR, BD.PROJECTED_DATE) 
        < MAX(BD.DAILY_PLAN) OVER (PARTITION BY BD.STORE_NBR, BD.PROJECTED_DATE) THEN 'UNDER'
      ELSE 'COMPLIANT'
    END AS PLAN_COMPLIANCE_FLAG
    
  FROM BASE_DATA AS BD
    INNER JOIN `enterprise-dw.location_dims.store_dim_cur` AS STR
      ON BD.DEST_LOC_ID = STR.STORE_NBR
      AND STR.CURRENT_IND = 'Y'
      AND STR.COUNTRY_CODE = 'US'
    INNER JOIN `enterprise-dw.location_dims.dc_dim` AS DC
      ON BD.ORIG_LOC_ID = DC.DC_NBR
    LEFT JOIN DAILY_ROLLUP AS DLY
      ON BD.DEST_LOC_ID = DLY.STORE_NBR
      AND BD.PROJECTED_DATE = DLY.PROJECTED_DATE
    LEFT JOIN WEEKLY_ROLLUP AS WKLY
      ON BD.DEST_LOC_ID = WKLY.STORE_NBR
      AND BD.PROJECTED_YEAR_WK_NBR = WKLY.PROJECTED_YEAR_WK_NBR
);
